/* Generated By:JJTree: Do not edit this line. ASTCodeBlock.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compilerproject;

public
class ASTCodeBlock extends SimpleNode {
  public ASTCodeBlock(int id) {
    super(id);
  }

  public ASTCodeBlock(MyNewGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c51bb3878e47709a86249ab417642ae5 (do not edit this line) */
