/* Generated By:JJTree: Do not edit this line. ASTDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compilerproject;

public
class ASTDeclaration extends SimpleNode {
  public ASTDeclaration(int id) {
    super(id);
  }

  public ASTDeclaration(MyNewGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b9279609a0e9c22e456846a26c06ad14 (do not edit this line) */
