/* Generated By:JJTree: Do not edit this line. ASTLoopIf.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compilerproject;

public
class ASTLoopIf extends SimpleNode {
  public ASTLoopIf(int id) {
    super(id);
  }

  public ASTLoopIf(MyNewGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d1f67ef3cee8a72601985c296a3f119 (do not edit this line) */
