/* Generated By:JJTree: Do not edit this line. ASTOutString.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compilerproject;

public
class ASTOutString extends SimpleNode {
  public ASTOutString(int id) {
    super(id);
  }

  public ASTOutString(MyNewGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2731c6f4d7ba846a854ecf8b70aa0fbf (do not edit this line) */
