/* Generated By:JJTree: Do not edit this line. ASTSwitchFor.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compilerproject;

public
class ASTSwitchFor extends SimpleNode {
  public ASTSwitchFor(int id) {
    super(id);
  }

  public ASTSwitchFor(MyNewGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3190c287f974f72f919662a8a4520504 (do not edit this line) */
