/* Generated By:JJTree: Do not edit this line. ASTVariablesBlock.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package compilerproject;

public
class ASTVariablesBlock extends SimpleNode {
  public ASTVariablesBlock(int id) {
    super(id);
  }

  public ASTVariablesBlock(MyNewGrammar p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=60db8a2559e60e74b7e3490264578aa3 (do not edit this line) */
