/* Generated By:JavaCC: Do not edit this line. CLParserTreeConstants.java Version 7.0.12 */
public interface CLParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVARIABLESBLOCK = 1;
  public int JJTVARDECL = 2;
  public int JJTTYPE = 3;
  public int JJTCODEBLOCK = 4;
  public int JJTSTATEMENT = 5;
  public int JJTASSIGNMENT = 6;
  public int JJTOUTPUT = 7;
  public int JJTLOOPIF = 8;
  public int JJTSWITCHFOR = 9;
  public int JJTCASEBRANCH = 10;
  public int JJTCONSTANTVALUE = 11;
  public int JJTCONDEXPRESSION = 12;
  public int JJTSIMPLEOPERAND = 13;
  public int JJTRELOP = 14;


  public String[] jjtNodeName = {
    "Program",
    "VariablesBlock",
    "VarDecl",
    "Type",
    "CodeBlock",
    "Statement",
    "Assignment",
    "Output",
    "Loopif",
    "SwitchFor",
    "CaseBranch",
    "ConstantValue",
    "CondExpression",
    "SimpleOperand",
    "RelOp",
  };
}
/* JavaCC - OriginalChecksum=8cf5d8aefb09a3556a5d916cd20f3bd2 (do not edit this line) */
