/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 7.0.12 */
package compilerproject;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVARIABLESBLOCK = 1;
  public int JJTDECLARATION = 2;
  public int JJTCODEBLOCK = 3;
  public int JJTSTATEMENT = 4;
  public int JJTASSIGNMENT = 5;
  public int JJTOUTSTRING = 6;
  public int JJTLOOPIF = 7;
  public int JJTLOOPIFBODY = 8;
  public int JJTSWITCHFOR = 9;
  public int JJTSWITCHBODY = 10;
  public int JJTCONDITION = 11;
  public int JJTEXPRESSION = 12;
  public int JJTTERM = 13;
  public int JJTFACTOR = 14;


  public String[] jjtNodeName = {
    "Start",
    "VariablesBlock",
    "Declaration",
    "CodeBlock",
    "Statement",
    "Assignment",
    "OutString",
    "LoopIf",
    "LoopIfBody",
    "SwitchFor",
    "SwitchBody",
    "Condition",
    "Expression",
    "Term",
    "Factor",
  };
}
/* JavaCC - OriginalChecksum=10d39f99ab765a07a9c9f0d9a41905e0 (do not edit this line) */
