/* MyNewGrammar.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. MyNewGrammar.java */
package compilerproject;

import java.util.ArrayList;

public class MyNewGrammar/*@bgen(jjtree)*/implements MyNewGrammarTreeConstants, MyNewGrammarConstants {/*@bgen(jjtree)*/
  protected JJTMyNewGrammarState jjtree = new JJTMyNewGrammarState();public SymbolTable symbolTable = new SymbolTable();
    public SemanticAnalyzer semanticAnalyzer = new SemanticAnalyzer(symbolTable);
    public IRGenerator irGenerator = new IRGenerator();

    public static void main(String args[]) throws ParseException {
        System.out.println("CL Parser - Milestone 2");
        try {
            java.io.InputStream input = (args.length > 0)
                ? new java.io.FileInputStream(args[0])
                : System.in;

            MyNewGrammar parser = new MyNewGrammar(input);

            /* Parse and get root of parse tree */
            SimpleNode root = parser.Start();

            System.out.println("\nSUCCESS: Code parsed successfully!");

            /* Print parse tree */
            System.out.println("\n--- PARSE TREE ---");
            root.dump("  ");

            /* Print semantic summary */
            parser.semanticAnalyzer.printSummary();

            /* Print original IR */
            parser.irGenerator.printIR();

            /* --- MILESTONE 2: OPTIMIZATION --- */
            Optimizer optimizer = new Optimizer(parser.irGenerator.getQuadruples());
            optimizer.optimize();
            optimizer.printOptimized();

            /* --- MILESTONE 2: TARGET CODE GENERATION --- */
            TargetCodeGenerator codeGen = new TargetCodeGenerator(
                optimizer.getOptimizedInstructions()
            );
            codeGen.generate();
            codeGen.printAssembly();

        } catch (java.io.FileNotFoundException e) {
            System.out.println("ERROR: File not found - " + e.getMessage());
        } catch (Exception e) {
            System.out.println("\nERROR: " + e.getMessage());
            e.printStackTrace();
        }
    }

/* ============================= */
/*        GRAMMAR RULES          */
/* ============================= */

/*
 * Start - Root of the parse tree
 * Returns SimpleNode so main() can call root.dump()
 */
  final public SimpleNode Start() throws ParseException {/*@bgen(jjtree) Start */
  SimpleNode jjtn000 = new SimpleNode(JJTSTART);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(START_PROG);
      VariablesBlock();
      CodeBlock();
      jj_consume_token(END_PROG);
      jj_consume_token(0);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return jjtn000;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/*
 * VariablesBlock - variables: section
 */
  final public void VariablesBlock() throws ParseException {/*@bgen(jjtree) VariablesBlock */
  SimpleNode jjtn000 = new SimpleNode(JJTVARIABLESBLOCK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(VAR_SECTION);
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case INT_TYPE:
        case FLOAT_TYPE:
        case CHAR_TYPE:
        case STRING_TYPE:{
          ;
          break;
          }
        default:
          jj_la1[0] = jj_gen;
          break label_1;
        }
        Declaration();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*
 * Declaration - single variable declaration
 *
 * FIX: Now emits IR instruction for the declaration.
 * Example IR: (=, 3, , abc)  means  abc = 3
 */
  final public void Declaration() throws ParseException {/*@bgen(jjtree) Declaration */
                       SimpleNode jjtn000 = new SimpleNode(JJTDECLARATION);
                       boolean jjtc000 = true;
                       jjtree.openNodeScope(jjtn000);Token t; Token id; Token val;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT_TYPE:{
        t = jj_consume_token(INT_TYPE);
        break;
        }
      case FLOAT_TYPE:{
        t = jj_consume_token(FLOAT_TYPE);
        break;
        }
      case STRING_TYPE:{
        t = jj_consume_token(STRING_TYPE);
        break;
        }
      case CHAR_TYPE:{
        t = jj_consume_token(CHAR_TYPE);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      id = jj_consume_token(ID);
      jj_consume_token(ASSIGN);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NUMBER:{
        val = jj_consume_token(NUMBER);
        break;
        }
      case FLOAT_NUMBER:{
        val = jj_consume_token(FLOAT_NUMBER);
        break;
        }
      case STRING_LITERAL:{
        val = jj_consume_token(STRING_LITERAL);
        break;
        }
      case CHAR_LITERAL:{
        val = jj_consume_token(CHAR_LITERAL);
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(SEMICOLON);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
/* Register in symbol table via semantic analyser */
        semanticAnalyzer.declareVariable(id.image, t.image, val.image);

        /* FIX: Emit IR for declaration - was missing before */
        irGenerator.emit("=", val.image, "", id.image);
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*
 * CodeBlock - code: section
 */
  final public void CodeBlock() throws ParseException {/*@bgen(jjtree) CodeBlock */
  SimpleNode jjtn000 = new SimpleNode(JJTCODEBLOCK);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(CODE_SECTION);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case SWITCHFOR:
        case OUTSTRING:
        case LPAREN:
        case FLOAT_NUMBER:
        case NUMBER:
        case STRING_LITERAL:
        case CHAR_LITERAL:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          break label_2;
        }
        Statement();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*
 * Statement - routes to correct statement type
 */
  final public void Statement() throws ParseException {/*@bgen(jjtree) Statement */
  SimpleNode jjtn000 = new SimpleNode(JJTSTATEMENT);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      if (jj_2_1(2147483647)) {
        Assignment();
      } else if (jj_2_2(2147483647)) {
        LoopIf();
      } else if (jj_2_3(2147483647)) {
        SwitchFor();
      } else if (jj_2_4(2147483647)) {
        OutString();
      } else {
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*
 * Assignment - variable = expression
 * IR: emits (=, exprResult, , varName)
 */
  final public void Assignment() throws ParseException {/*@bgen(jjtree) Assignment */
                      SimpleNode jjtn000 = new SimpleNode(JJTASSIGNMENT);
                      boolean jjtc000 = true;
                      jjtree.openNodeScope(jjtn000);Token id; String exprResult;
    try {
      id = jj_consume_token(ID);
semanticAnalyzer.checkAssignment(id.image);
      jj_consume_token(ASSIGN);
      exprResult = Expression();
      jj_consume_token(SEMICOLON);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
irGenerator.emit("=", exprResult, "", id.image);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*
 * OutString - outString(expr) or outString("string")
 *
 * FIX: Expression() return value was being discarded before.
 * Now captured and emitted as a PRINT instruction.
 */
  final public void OutString() throws ParseException {/*@bgen(jjtree) OutString */
                     SimpleNode jjtn000 = new SimpleNode(JJTOUTSTRING);
                     boolean jjtc000 = true;
                     jjtree.openNodeScope(jjtn000);String res; Token t;
    try {
      jj_consume_token(OUTSTRING);
      jj_consume_token(LPAREN);
      if (jj_2_5(2)) {
        res = Expression();
irGenerator.emit("print", res, "", "");
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case STRING_LITERAL:{
          t = jj_consume_token(STRING_LITERAL);
irGenerator.emit("print", t.image, "", "");
          break;
          }
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOLON);
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*
 * LoopIf - loopif condition holds ... endloop
 *
 * FIX: Now generates proper loop IR with labels and goto.
 *
 * IR generated:
 *   label  L1             <- loop start label
 *   <op>   left  right  t1  <- condition evaluation
 *   ifFalse t1    L1_end  <- exit loop if condition false
 *   ... body statements ...
 *   goto   L1             <- jump back to start
 *   label  L1_end         <- loop end label
 */
  final public void LoopIf() throws ParseException {/*@bgen(jjtree) LoopIf */
                  SimpleNode jjtn000 = new SimpleNode(JJTLOOPIF);
                  boolean jjtc000 = true;
                  jjtree.openNodeScope(jjtn000);String condResult; String loopLabel; String endLabel;
    try {
/* Generate loop labels BEFORE parsing condition */
        loopLabel = "L" + irGenerator.newTemp();
        endLabel  = loopLabel + "_end";
        irGenerator.emit("label", loopLabel, "", "");
      condResult = Condition();
/* If condition is false, jump to end of loop */
        irGenerator.emit("ifFalse", condResult, "", endLabel);
      jj_consume_token(HOLDS);
      label_3:
      while (true) {
        LoopIfBody();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case OUTSTRING:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[5] = jj_gen;
          break label_3;
        }
      }
      jj_consume_token(ENDLOOP);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
/* Jump back to loop start to recheck condition */
        irGenerator.emit("goto", "", "", loopLabel);
        irGenerator.emit("label", endLabel, "", "");
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*
 * LoopIfBody - only Assignment and OutString inside loop
 * Enforces no-nesting rule from PDF
 */
  final public void LoopIfBody() throws ParseException {/*@bgen(jjtree) LoopIfBody */
  SimpleNode jjtn000 = new SimpleNode(JJTLOOPIFBODY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      if (jj_2_6(2)) {
        Assignment();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case OUTSTRING:{
          OutString();
          break;
          }
        default:
          jj_la1[6] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*
 * SwitchFor - switchFor(var) case ... other ... endswitchFor
 *
 * IR generated:
 *   switch  varName
 *   case    value
 *   ... assignment ...
 *   endswitch
 */
  final public void SwitchFor() throws ParseException {/*@bgen(jjtree) SwitchFor */
                     SimpleNode jjtn000 = new SimpleNode(JJTSWITCHFOR);
                     boolean jjtc000 = true;
                     jjtree.openNodeScope(jjtn000);Token id;
    try {
      jj_consume_token(SWITCHFOR);
      jj_consume_token(LPAREN);
      id = jj_consume_token(ID);
semanticAnalyzer.checkVariableDeclared(id.image);
      jj_consume_token(RPAREN);
irGenerator.emit("switch", id.image, "", "");
      label_4:
      while (true) {
        jj_consume_token(CASE);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NUMBER:{
          jj_consume_token(NUMBER);
          break;
          }
        case FLOAT_NUMBER:{
          jj_consume_token(FLOAT_NUMBER);
          break;
          }
        case STRING_LITERAL:{
          jj_consume_token(STRING_LITERAL);
          break;
          }
        case CHAR_LITERAL:{
          jj_consume_token(CHAR_LITERAL);
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(COLON);
        SwitchBody();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CASE:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_4;
        }
      }
      jj_consume_token(OTHER);
      jj_consume_token(COLON);
      SwitchBody();
      jj_consume_token(ENDSWITCH);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
irGenerator.emit("endswitch", "", "", "");
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*
 * SwitchBody - statements inside a case or other branch
 * No nesting allowed
 */
  final public void SwitchBody() throws ParseException {/*@bgen(jjtree) SwitchBody */
  SimpleNode jjtn000 = new SimpleNode(JJTSWITCHBODY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      label_5:
      while (true) {
        if (jj_2_7(2)) {
          Assignment();
        } else {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case OUTSTRING:{
            OutString();
            break;
            }
          default:
            jj_la1[9] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case OUTSTRING:
        case ID:{
          ;
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          break label_5;
        }
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
}

/*
 * Condition - conditional expression used in loopif
 *
 * FIX: Now captures both Expression() results and the operator.
 * Emits a comparison IR instruction.
 * Returns the temp variable holding the boolean result.
 *
 * IR example for "num > 0":
 *   (>, num, 0, t1)
 */
  final public String Condition() throws ParseException {/*@bgen(jjtree) Condition */
                       SimpleNode jjtn000 = new SimpleNode(JJTCONDITION);
                       boolean jjtc000 = true;
                       jjtree.openNodeScope(jjtn000);String left, right; Token op; String res;
    try {
      left = Expression();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQUALS:{
        op = jj_consume_token(EQUALS);
        break;
        }
      case LE:{
        op = jj_consume_token(LE);
        break;
        }
      case GE:{
        op = jj_consume_token(GE);
        break;
        }
      case NE:{
        op = jj_consume_token(NE);
        break;
        }
      case LT:{
        op = jj_consume_token(LT);
        break;
        }
      case GT:{
        op = jj_consume_token(GT);
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      right = Expression();
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
res = irGenerator.newTemp();
        irGenerator.emit(op.image, left, right, res);
        {if ("" != null) return res;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/*
 * Expression - addition and subtraction (lowest precedence)
 *
 * Returns the temp variable or operand holding the result.
 * IR example for "abc + xyz":
 *   (+, abc, xyz, t1)
 */
  final public String Expression() throws ParseException {/*@bgen(jjtree) Expression */
                        SimpleNode jjtn000 = new SimpleNode(JJTEXPRESSION);
                        boolean jjtc000 = true;
                        jjtree.openNodeScope(jjtn000);String t1, t2; Token op;
    try {
      t1 = Term();
      label_6:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PLUS:
        case MINUS:{
          ;
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          break label_6;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case PLUS:{
          op = jj_consume_token(PLUS);
          break;
          }
        case MINUS:{
          op = jj_consume_token(MINUS);
          break;
          }
        default:
          jj_la1[13] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        t2 = Term();
String res = irGenerator.newTemp();
            irGenerator.emit(op.image, t1, t2, res);
            t1 = res;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return t1;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/*
 * Term - multiplication and division (higher precedence)
 *
 * Returns the temp variable or operand holding the result.
 * IR example for "fact * num":
 *   (*, fact, num, t1)
 */
  final public String Term() throws ParseException {/*@bgen(jjtree) Term */
                  SimpleNode jjtn000 = new SimpleNode(JJTTERM);
                  boolean jjtc000 = true;
                  jjtree.openNodeScope(jjtn000);String t1, t2; Token op;
    try {
      t1 = Factor();
      label_7:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case MULT:
        case DIV:{
          ;
          break;
          }
        default:
          jj_la1[14] = jj_gen;
          break label_7;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case MULT:{
          op = jj_consume_token(MULT);
          break;
          }
        case DIV:{
          op = jj_consume_token(DIV);
          break;
          }
        default:
          jj_la1[15] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        t2 = Factor();
String res = irGenerator.newTemp();
            irGenerator.emit(op.image, t1, t2, res);
            t1 = res;
      }
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return t1;}
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

/*
 * Factor - a single unit in an expression
 *
 * Returns the actual value string (variable name or literal).
 * No IR emitted here — the value is passed up to Expression/Term.
 */
  final public String Factor() throws ParseException {/*@bgen(jjtree) Factor */
                    SimpleNode jjtn000 = new SimpleNode(JJTFACTOR);
                    boolean jjtc000 = true;
                    jjtree.openNodeScope(jjtn000);Token t; String res;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NUMBER:{
        t = jj_consume_token(NUMBER);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return t.image;}
        break;
        }
      case FLOAT_NUMBER:{
        t = jj_consume_token(FLOAT_NUMBER);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return t.image;}
        break;
        }
      case ID:{
        t = jj_consume_token(ID);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
semanticAnalyzer.checkVariableDeclared(t.image);
        {if ("" != null) return t.image;}
        break;
        }
      case STRING_LITERAL:{
        t = jj_consume_token(STRING_LITERAL);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return t.image;}
        break;
        }
      case CHAR_LITERAL:{
        t = jj_consume_token(CHAR_LITERAL);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return t.image;}
        break;
        }
      case LPAREN:{
        jj_consume_token(LPAREN);
        res = Expression();
        jj_consume_token(RPAREN);
jjtree.closeNodeScope(jjtn000, true);
      jjtc000 = false;
{if ("" != null) return res;}
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (Throwable jjte000) {
if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_3R_Term_370_5_10()
 {
    if (jj_3R_Factor_392_5_12()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Term_372_9_13()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_Factor_410_7_19()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_Expression_347_5_8()) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_3R_Assignment_194_5_9()) return true;
    return false;
  }

  private boolean jj_3R_Factor_407_7_18()
 {
    if (jj_scan_token(CHAR_LITERAL)) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_Expression_347_5_8()) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_Assignment_194_5_9()) return true;
    return false;
  }

  private boolean jj_3R_Factor_404_7_17()
 {
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_Expression_349_9_11()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(25)) {
    jj_scanpos = xsp;
    if (jj_scan_token(26)) return true;
    }
    return false;
  }

  private boolean jj_3R_Factor_398_7_16()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3R_Factor_395_7_15()
 {
    if (jj_scan_token(FLOAT_NUMBER)) return true;
    return false;
  }

  private boolean jj_3R_Expression_347_5_8()
 {
    if (jj_3R_Term_370_5_10()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_Expression_349_9_11()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_Factor_392_5_12()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_Factor_392_5_14()) {
    jj_scanpos = xsp;
    if (jj_3R_Factor_395_7_15()) {
    jj_scanpos = xsp;
    if (jj_3R_Factor_398_7_16()) {
    jj_scanpos = xsp;
    if (jj_3R_Factor_404_7_17()) {
    jj_scanpos = xsp;
    if (jj_3R_Factor_407_7_18()) {
    jj_scanpos = xsp;
    if (jj_3R_Factor_410_7_19()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_Factor_392_5_14()
 {
    if (jj_scan_token(NUMBER)) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_scan_token(OUTSTRING)) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_scan_token(SWITCHFOR)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_scan_token(LOOPIF)) return true;
    return false;
  }

  private boolean jj_3R_Assignment_194_5_9()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(ASSIGN)) return true;
    return false;
  }

  private boolean jj_3R_Term_372_9_13()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(27)) {
    jj_scanpos = xsp;
    if (jj_scan_token(28)) return true;
    }
    return false;
  }

  /** Generated Token Manager. */
  public MyNewGrammarTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[17];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x1e00,0x1e00,0x0,0x910000,0x0,0x100000,0x100000,0x0,0x40000,0x100000,0x100000,0xe0000000,0x6000000,0x6000000,0x18000000,0x18000000,0x800000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0xf0,0x1f0,0x40,0x100,0x0,0xf0,0x0,0x0,0x100,0x7,0x0,0x0,0x0,0x0,0x1f0,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[7];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public MyNewGrammar(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public MyNewGrammar(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new MyNewGrammarTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public MyNewGrammar(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new MyNewGrammarTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new MyNewGrammarTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public MyNewGrammar(MyNewGrammarTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(MyNewGrammarTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jjtree.reset();
	 jj_gen = 0;
	 for (int i = 0; i < 17; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[41];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 17; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 41; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 7; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
