/* Generated By:JJTree&JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package compilerproject;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int START_PROG = 5;
  /** RegularExpression Id. */
  int END_PROG = 6;
  /** RegularExpression Id. */
  int VAR_SECTION = 7;
  /** RegularExpression Id. */
  int CODE_SECTION = 8;
  /** RegularExpression Id. */
  int INT_TYPE = 9;
  /** RegularExpression Id. */
  int STRING_TYPE = 10;
  /** RegularExpression Id. */
  int LOOPIF = 11;
  /** RegularExpression Id. */
  int HOLDS = 12;
  /** RegularExpression Id. */
  int ENDLOOP = 13;
  /** RegularExpression Id. */
  int SWITCHFOR = 14;
  /** RegularExpression Id. */
  int ENDSWITCH = 15;
  /** RegularExpression Id. */
  int CASE = 16;
  /** RegularExpression Id. */
  int OTHER = 17;
  /** RegularExpression Id. */
  int OUTSTRING = 18;
  /** RegularExpression Id. */
  int SEMICOLON = 19;
  /** RegularExpression Id. */
  int COLON = 20;
  /** RegularExpression Id. */
  int LPAREN = 21;
  /** RegularExpression Id. */
  int RPAREN = 22;
  /** RegularExpression Id. */
  int PLUS = 23;
  /** RegularExpression Id. */
  int MINUS = 24;
  /** RegularExpression Id. */
  int MULT = 25;
  /** RegularExpression Id. */
  int DIV = 26;
  /** RegularExpression Id. */
  int EQUALS = 27;
  /** RegularExpression Id. */
  int LE = 28;
  /** RegularExpression Id. */
  int GE = 29;
  /** RegularExpression Id. */
  int NE = 30;
  /** RegularExpression Id. */
  int LT = 31;
  /** RegularExpression Id. */
  int GT = 32;
  /** RegularExpression Id. */
  int ASSIGN = 33;
  /** RegularExpression Id. */
  int NUMBER = 34;
  /** RegularExpression Id. */
  int STRING_LITERAL = 35;
  /** RegularExpression Id. */
  int ID = 36;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"startProgram\"",
    "\"endProgram\"",
    "\"variables:\"",
    "\"code:\"",
    "\"int\"",
    "\"string\"",
    "\"loopif\"",
    "\"holds\"",
    "\"endloop\"",
    "\"switchFor\"",
    "\"endswitchFor\"",
    "\"case\"",
    "\"other\"",
    "\"outString\"",
    "\";\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "<NUMBER>",
    "<STRING_LITERAL>",
    "<ID>",
  };

}
