/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package compilerproject;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int START_PROG = 5;
  /** RegularExpression Id. */
  int END_PROG = 6;
  /** RegularExpression Id. */
  int VAR_SECTION = 7;
  /** RegularExpression Id. */
  int CODE_SECTION = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int ID = 10;
  /** RegularExpression Id. */
  int NUMBER = 11;
  /** RegularExpression Id. */
  int ASSIGN = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"startProgram\"",
    "\"endProgram\"",
    "\"variables:\"",
    "\"code:\"",
    "\"int\"",
    "<ID>",
    "<NUMBER>",
    "\"=\"",
    "\";\"",
  };

}
