/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 7.0.12 */
package compilerproject;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVARIABLESBLOCK = 1;
  public int JJTDECLARATION = 2;
  public int JJTCODEBLOCK = 3;
  public int JJTVOID = 4;
  public int JJTASSIGNMENT = 5;
  public int JJTOUTSTRING = 6;
  public int JJTLOOPIF = 7;
  public int JJTSWITCHFOR = 8;
  public int JJTCONDITION = 9;
  public int JJTEXPRESSION = 10;
  public int JJTTERM = 11;
  public int JJTFACTOR = 12;


  public String[] jjtNodeName = {
    "Start",
    "VariablesBlock",
    "Declaration",
    "CodeBlock",
    "void",
    "Assignment",
    "OutString",
    "LoopIf",
    "SwitchFor",
    "Condition",
    "Expression",
    "Term",
    "Factor",
  };
}
/* JavaCC - OriginalChecksum=bea8d6fbbab40761451ae395e9660117 (do not edit this line) */
